# Generated by Django 4.1.4 on 2022-12-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alumno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='sueldo',
            field=models.FloatField(null=True),
        ),
    ]
